[general]
maxBufSize = 1024
userAgent = "Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.3112.90 Safari/537.36"

[redis]
addr = "YOUR_IP"
password = "YOUR_PASS"

[requester]
maxConn = 16